name: deno-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fluxy-fresh
          entrypoint: main.ts
